/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.mycompany.financeiro.frmTipoDespesa;


import com.mycompany.financeiro.dao.tipodespesa;
import com.mycompany.financeiro.dao.utilidades.conexao;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.UIManager.getString;

/**
 *
 * @author luiz.souza
 */
public final class frmTipoDespesa extends javax.swing.JFrame {
    public int posicaoDespesas=0;
    List<tipodespesa> despesas = new ArrayList<>();
    public ResultSet resultado;
    public int codigo;
    public boolean carregaCBDespesa = true;
    HashMap cbDespesaMapa =new HashMap();
    /**
     * Creates new form frmFornecedores
     */
    public frmTipoDespesa() {
        initComponents();
        despesas=carregaDespesas();
        mostrarDespesas(despesas,posicaoDespesas);
        travaredicaoCamposDespesas();
        carregarcbDespesas();
    }
public List<tipodespesa> carregaDespesas(){
        conexao con = new conexao();
        con.conecta();
        resultado = con.executaConsulta("select * from tipodespesa order by NomeDespesa");
        ////System.out.print("\nEntrei no carregaFornecedores() \n");
        despesas.clear();
        try
        {
        while (resultado.next())
        {
          //  //System.out.print("\n Entrei no while do carregaFornecedores()\n");
            
            tipodespesa atual = new tipodespesa();
            atual.setIdTipoDespesa(resultado.getInt("IdTipoDespesa"));
            atual.setNomeDespesa(resultado.getString("NomeDespesa"));
            atual.setObservaçãoDespesa(resultado.getString("ObservacaoDespesa"));
            atual.setTipoDespesa(resultado.getString("TipoDespesa"));
            despesas.add(atual);
        ////System.out.print("\nLendo registros: "+fornecedores.size());
        }
        ////System.out.print("\nSaindo do while: ");
        }
    catch (SQLException e)
    {
        JOptionPane.showMessageDialog(null, e);
    }
     posicaoDespesas=0;
     ////System.out.print("\nRegistros lidos: "+fornecedores.size());
     return despesas;
        }
public void mostrarDespesas(List<tipodespesa> despesas,int posicaoDespesas)
{
    if ((despesas.size())<1)
    {
    JOptionPane.showMessageDialog(null, "Não há registros suficientes para exibição "+(despesas.size()));
    }
    else
    {
    ////System.out.print("\nposicao:"+posicaoFornecedores+"\n");
    tf_Id.setText(String.valueOf(despesas.get(posicaoDespesas).getIdTipoDespesa()));
    tf_Nome.setText(despesas.get(posicaoDespesas).getNomeDespesa());
    tf_Observacao.setText(despesas.get(posicaoDespesas).getObservaçãoDespesa());
    
    
    if (despesas.get(posicaoDespesas).getTipoDespesa().equals("C"))
    {
        cb_tipo.setSelectedIndex(0);
    }
    
    if (despesas.get(posicaoDespesas).getTipoDespesa().equals("L"))
    {
        cb_tipo.setSelectedIndex(1);
    }
    
    if (despesas.get(posicaoDespesas).getTipoDespesa().equals("M"))
    {
        cb_tipo.setSelectedIndex(2);
    }
    }

}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf_Id = new javax.swing.JTextField();
        tf_Nome = new javax.swing.JTextField();
        lbl_Id = new javax.swing.JLabel();
        lbl_Nome = new javax.swing.JLabel();
        btn_Anterior = new javax.swing.JButton();
        btn_Proximo = new javax.swing.JButton();
        lbl_Obs = new javax.swing.JLabel();
        tf_Observacao = new javax.swing.JTextField();
        btn_Ultimo = new javax.swing.JToggleButton();
        btn_Primeiro = new javax.swing.JButton();
        btn_Novo = new javax.swing.JButton();
        btn_salvar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        cb_despesas = new javax.swing.JComboBox<>();
        btn_Excluir = new javax.swing.JButton();
        btn_Editar = new javax.swing.JButton();
        lbl_Id1 = new javax.swing.JLabel();
        cb_tipo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tf_Id.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tf_Id.setText("jTextField1");

        tf_Nome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tf_Nome.setText("jTextField2");

        lbl_Id.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_Id.setText("ID:");

        lbl_Nome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_Nome.setText("Nome:");

        btn_Anterior.setText("Anterior");
        btn_Anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AnteriorActionPerformed(evt);
            }
        });

        btn_Proximo.setText("Próximo");
        btn_Proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ProximoActionPerformed(evt);
            }
        });

        lbl_Obs.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_Obs.setText("Observação:");

        tf_Observacao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tf_Observacao.setText("jTextField5");
        tf_Observacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_ObservacaoActionPerformed(evt);
            }
        });

        btn_Ultimo.setText("Último");
        btn_Ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UltimoActionPerformed(evt);
            }
        });

        btn_Primeiro.setText("Primeiro");
        btn_Primeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PrimeiroActionPerformed(evt);
            }
        });

        btn_Novo.setText("Novo");
        btn_Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NovoActionPerformed(evt);
            }
        });

        btn_salvar.setText("Salvar");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tipos de Despesas:");

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jButton2.setMnemonic('p');
        jButton2.setText("Pesquisa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cb_despesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_despesasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb_despesas, 0, 635, Short.MAX_VALUE)
                .addGap(35, 35, 35)
                .addComponent(jButton2)
                .addGap(83, 83, 83))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_despesas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18))
        );

        btn_Excluir.setText("Excluir");
        btn_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExcluirActionPerformed(evt);
            }
        });

        btn_Editar.setText("Editar");
        btn_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditarActionPerformed(evt);
            }
        });

        lbl_Id1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_Id1.setText("Tipo:");

        cb_tipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Despesa de Casa", "Despesa da Loja", "Material para Venda" }));
        cb_tipo.setSelectedIndex(2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 883, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Novo)
                        .addGap(18, 18, 18)
                        .addComponent(btn_salvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Excluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Editar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Primeiro))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Nome)
                            .addComponent(lbl_Id)
                            .addComponent(lbl_Obs)
                            .addComponent(lbl_Id1))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_Observacao)
                            .addComponent(tf_Nome)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addComponent(btn_Anterior)
                .addGap(29, 29, 29)
                .addComponent(btn_Proximo)
                .addGap(18, 18, 18)
                .addComponent(btn_Ultimo)
                .addGap(72, 72, 72))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Nome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_Obs)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_Id1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tf_Observacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_tipo)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Ultimo)
                    .addComponent(btn_Proximo)
                    .addComponent(btn_Anterior)
                    .addComponent(btn_Primeiro)
                    .addComponent(btn_Novo)
                    .addComponent(btn_salvar)
                    .addComponent(btn_Excluir)
                    .addComponent(btn_Editar))
                .addGap(34, 34, 34)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(891, 420));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ProximoActionPerformed
   if (posicaoDespesas<despesas.size()-1)
        posicaoDespesas=posicaoDespesas+1;
        
            mostrarDespesas(despesas,posicaoDespesas);
    }//GEN-LAST:event_btn_ProximoActionPerformed

    private void btn_AnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AnteriorActionPerformed
if (posicaoDespesas>0)
    posicaoDespesas=posicaoDespesas-1;
        mostrarDespesas(despesas,posicaoDespesas);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_AnteriorActionPerformed

    private void btn_PrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PrimeiroActionPerformed
    posicaoDespesas=0;
        mostrarDespesas(despesas,posicaoDespesas);
    }//GEN-LAST:event_btn_PrimeiroActionPerformed

    private void btn_UltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UltimoActionPerformed
    posicaoDespesas=despesas.size()-1;
        mostrarDespesas(despesas,posicaoDespesas);
    }//GEN-LAST:event_btn_UltimoActionPerformed

    private void btn_NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NovoActionPerformed
    limpaCamposDespesas();
    liberaredicaoCamposDespesas();
    
    }//GEN-LAST:event_btn_NovoActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
    if (tf_Id.getText().isEmpty())
    {
      codigo= pegaUltimoCodigoDespesas()+1;
      ////System.out.print("\nBotao 1 codigo:"+codigo+"\n");
      String strTipoDespesa="";
      if (cb_tipo.getSelectedIndex()==0)
          strTipoDespesa="C";
      if (cb_tipo.getSelectedIndex()==1)
          strTipoDespesa="L";
      if (cb_tipo.getSelectedIndex()==2)
          strTipoDespesa="M";
          
          
        String SQL = "Insert into tipodespesa (IdTipoDespesa ,NomeDespesa,ObservacaoDespesa,TipoDespesa) values ("+codigo+",'"+
            tf_Nome.getText()+"','"+tf_Observacao.getText()+"','"+strTipoDespesa+"')";
    
    conexao con = new conexao();
    con.conecta();
    con.executaUpdate(SQL);
    
    limpaCamposDespesas();
    despesas=carregaDespesas();
    mostrarDespesas(despesas,posicaoDespesas);
    carregarcbDespesas();
    travaredicaoCamposDespesas();
    }
    else
    {
      String strTipoDespesa="";
      if (cb_tipo.getSelectedIndex()==0)
          strTipoDespesa="C";
      if (cb_tipo.getSelectedIndex()==1)
          strTipoDespesa="L";
      if (cb_tipo.getSelectedIndex()==2)
          strTipoDespesa="M";
      
      String SQL = "Update tipodespesa set IdTipoDespesa="+Integer.valueOf(tf_Id.getText())+
              ",NomeDespesa='"+tf_Nome.getText()+
              "',ObservacaoDespesa='"+tf_Observacao.getText()+
              "',TipoDespesa='"+strTipoDespesa+
              "' where IdTipoDespesa="+Integer.valueOf(tf_Id.getText());
           
      //System.out.print("\nSQL UPDATE:"+SQL);
    
    conexao con = new conexao();
    con.conecta();
    con.executaUpdate(SQL);
    limpaCamposDespesas();
    despesas=carregaDespesas();
    mostrarDespesas(despesas,posicaoDespesas);
    carregarcbDespesas();
    travaredicaoCamposDespesas();
//JOptionPane.showMessageDialog(null, "Implementar");
    }
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    mostrarDespesas(despesas,posicaoDespesas);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cb_despesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_despesasActionPerformed
        try {
            
            for (int i=0;i<=despesas.size()-1;i++)
            {
            ////System.out.print("\nFornecedores: "+cb_fornecedores.getSelectedItem().toString());
            ////System.out.print("\nCB: "+cb_fornecedores.getSelectedItem().toString());
                if (despesas.get(i).getNomeDespesa().equals(cb_despesas.getSelectedItem()))    
                        {
                            cbDespesaMapa.put("Nome", despesas.get(i).getNomeDespesa());
                            cbDespesaMapa.put("Id",i);
                        }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        ////System.out.print("\nChave ID: "+cbFornecedorMapa.get("Id").toString());
        //posicaoDespesas = Integer.parseUnsignedInt(cbDespesaMapa.get("Id").toString());
        posicaoDespesas = Integer.valueOf(cbDespesaMapa.get("Id").toString());
            mostrarDespesas(despesas,posicaoDespesas);
    }//GEN-LAST:event_cb_despesasActionPerformed

    private void btn_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExcluirActionPerformed
    conexao con = new conexao();
    con.conecta();
    con.executaUpdate("delete from tipodespesa where IdTipoDespesa="+tf_Id.getText());
    despesas.clear();
    despesas =carregaDespesas();
        mostrarDespesas(despesas, posicaoDespesas);
        carregarcbDespesas();
    }//GEN-LAST:event_btn_ExcluirActionPerformed

    private void tf_ObservacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_ObservacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_ObservacaoActionPerformed

    private void btn_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditarActionPerformed
     liberaredicaoCamposDespesas();
    }//GEN-LAST:event_btn_EditarActionPerformed
    public void carregarcbDespesas(){
        //if (carregaCBFornecedores==true)
        
        despesas = carregaDespesas();
        cb_despesas.removeAllItems();
        for (int i =0; i<=despesas.size()-1;i++)
        {
        cb_despesas.addItem(despesas.get(i).getNomeDespesa());
        }
                                            }
            
    public int pegaUltimoCodigoDespesas()
        {
         conexao con = new conexao();
         resultado = con.executaConsulta("Select IdTipoDespesa from tipodespesa order by IdTipoDespesa desc limit 1");
         
         try
         {
         ////System.out.print("\nIdTipoDespesa: "+resultado.getInt("IdTipoDespesa"));
         codigo = (resultado.getInt("IdTipoDespesa")+1);
         ////System.out.print("\n Ultimo codigo:"+codigo);
         con.resultado.close();
         }
         catch (Exception e)
         {
         JOptionPane.showMessageDialog(null, e);
         }
        ////System.out.print("\npegaUltimoCodigoForenecedores: "+codigo+"\n");
         return codigo;
        }
    /**
     * @param args the command line arguments
     */
    public void limpaCamposDespesas()
    { 
    tf_Id.setText("");
    tf_Nome.setText("");
    tf_Observacao.setText("");
    tf_Nome.requestFocus();
    }
    
     public void travaredicaoCamposDespesas()
    { 
    
    tf_Id.setEnabled(false);
    tf_Nome.setEnabled(false);
    tf_Observacao.setEnabled(false);
    cb_tipo.setEnabled(false);
    tf_Nome.setEnabled(false);
    }
     
    public void liberaredicaoCamposDespesas()
    { 
    tf_Id.setEnabled(true);
    tf_Nome.setEnabled(true);
    tf_Observacao.setEnabled(true);
    cb_tipo.setEnabled(true);
    tf_Nome.setEnabled(true);
    } 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTipoDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTipoDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTipoDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTipoDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTipoDespesa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Anterior;
    private javax.swing.JButton btn_Editar;
    private javax.swing.JButton btn_Excluir;
    private javax.swing.JButton btn_Novo;
    private javax.swing.JButton btn_Primeiro;
    private javax.swing.JButton btn_Proximo;
    private javax.swing.JToggleButton btn_Ultimo;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JComboBox<String> cb_despesas;
    private javax.swing.JComboBox<String> cb_tipo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_Id;
    private javax.swing.JLabel lbl_Id1;
    private javax.swing.JLabel lbl_Nome;
    private javax.swing.JLabel lbl_Obs;
    private javax.swing.JTextField tf_Id;
    private javax.swing.JTextField tf_Nome;
    private javax.swing.JTextField tf_Observacao;
    // End of variables declaration//GEN-END:variables
}

