/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.financeiro.frmFornecedores;

import com.mycompany.financeiro.dao.fornecedores;
import com.mycompany.financeiro.dao.utilidades.conexao;
import static java.lang.constant.ConstantDescs.NULL;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import static javax.swing.UIManager.getString;

/**
 *
 * @author luiz.souza
 */
public class frmFornecedores extends javax.swing.JFrame {
    public int posicaoFornecedores=0;
    List<fornecedores> fornecedores = new ArrayList<>();
    public ResultSet resultado;
    public int codigo;
    public boolean carregaCBFornecedores = true;
    HashMap cbFornecedorMapa =new HashMap();
    /**
     * Creates new form frmFornecedores
     */
    public frmFornecedores() {
        initComponents();
        fornecedores=carregaFornecedores();
        mostrarFornecedores(fornecedores,posicaoFornecedores);
        travaredicaoCamposFornecedores();
        carregarcbFornecedores();
    }
public List<fornecedores> carregaFornecedores(){
        conexao con = new conexao();
        con.conecta();
        resultado = con.executaConsulta("select * from fornecedores order by NomeFornecedor ");
        ////System.out.print("\nEntrei no carregaFornecedores() \n");
        fornecedores.clear();
        try
        {
        while (resultado.next())
        {
          //  //System.out.print("\n Entrei no while do carregaFornecedores()\n");
            
            fornecedores atual = new fornecedores();
            atual.setEnderecoFornecedor(resultado.getString("EnderecoFornecedor"));
            atual.setIdFornecedor(resultado.getInt("IdFornecedor"));
            atual.setNomeFornecedor(resultado.getString("NomeFornecedor"));
            atual.setFoneFornecedor(resultado.getString("FoneFornecedor"));
            atual.setObservacoesfornecedor(resultado.getString("Observacoesfornecedor"));
        fornecedores.add(atual);
        ////System.out.print("\nLendo registros: "+fornecedores.size());
        }
        ////System.out.print("\nSaindo do while: ");
        }
    catch (SQLException e)
    {
        JOptionPane.showMessageDialog(null, e);
    }
     posicaoFornecedores=0;
     ////System.out.print("\nRegistros lidos: "+fornecedores.size());
     return fornecedores;
        }
public void mostrarFornecedores(List<fornecedores> fornecedores,int posicaoFornecedores)
{
    if ((fornecedores.size())<1)
    {
    JOptionPane.showMessageDialog(null, "Não há registros suficientes para exibição "+(fornecedores.size()-1));
    }
    else
    {
    ////System.out.print("\nposicao:"+posicaoFornecedores+"\n");
    tf_Id.setText(String.valueOf(fornecedores.get(posicaoFornecedores).getIdFornecedor()));
    tf_Nome.setText(fornecedores.get(posicaoFornecedores).getNomeFornecedor());
    tf_Endereco.setText(fornecedores.get(posicaoFornecedores).getEnderecoFornecedor());
    tf_Fone.setText(fornecedores.get(posicaoFornecedores).getFoneFornecedor());
    tf_Observacao.setText(fornecedores.get(posicaoFornecedores).getObservacoesfornecedor());
    
    }   

}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf_Id = new javax.swing.JTextField();
        tf_Nome = new javax.swing.JTextField();
        tf_Endereco = new javax.swing.JTextField();
        tf_Fone = new javax.swing.JTextField();
        lbl_Id = new javax.swing.JLabel();
        lbl_Nome = new javax.swing.JLabel();
        lbl_Endereco = new javax.swing.JLabel();
        lbl_Fone = new javax.swing.JLabel();
        btn_Anterior = new javax.swing.JButton();
        btn_Proximo = new javax.swing.JButton();
        lbl_Obs = new javax.swing.JLabel();
        tf_Observacao = new javax.swing.JTextField();
        btn_Ultimo = new javax.swing.JToggleButton();
        btn_Primeiro = new javax.swing.JButton();
        btn_Novo = new javax.swing.JButton();
        btn_Salvar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        cb_fornecedores = new javax.swing.JComboBox<>();
        btn_Excluir = new javax.swing.JButton();
        btn_Editar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tf_Id.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tf_Id.setText("jTextField1");

        tf_Nome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tf_Nome.setText("jTextField2");

        tf_Endereco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tf_Endereco.setText("jTextField3");

        tf_Fone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tf_Fone.setText("jTextField4");

        lbl_Id.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_Id.setText("ID:");

        lbl_Nome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_Nome.setText("Nome:");

        lbl_Endereco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_Endereco.setText("Endereço:");

        lbl_Fone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_Fone.setText("Fone:");

        btn_Anterior.setText("Anterior");
        btn_Anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AnteriorActionPerformed(evt);
            }
        });

        btn_Proximo.setText("Próximo");
        btn_Proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ProximoActionPerformed(evt);
            }
        });

        lbl_Obs.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_Obs.setText("Observação:");

        tf_Observacao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tf_Observacao.setText("jTextField5");
        tf_Observacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_ObservacaoActionPerformed(evt);
            }
        });

        btn_Ultimo.setText("Último");
        btn_Ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UltimoActionPerformed(evt);
            }
        });

        btn_Primeiro.setText("Primeiro");
        btn_Primeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PrimeiroActionPerformed(evt);
            }
        });

        btn_Novo.setText("Novo");
        btn_Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NovoActionPerformed(evt);
            }
        });

        btn_Salvar.setText("Salvar");
        btn_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalvarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Fornecedores:");

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jButton2.setMnemonic('p');
        jButton2.setText("Pesquisa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cb_fornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_fornecedoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb_fornecedores, 0, 635, Short.MAX_VALUE)
                .addGap(35, 35, 35)
                .addComponent(jButton2)
                .addGap(83, 83, 83))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_fornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18))
        );

        btn_Excluir.setText("Excluir");
        btn_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExcluirActionPerformed(evt);
            }
        });

        btn_Editar.setText("Editar");
        btn_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 883, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Novo)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Salvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Excluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Editar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Primeiro)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Anterior)
                        .addGap(29, 29, 29)
                        .addComponent(btn_Proximo)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Ultimo)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lbl_Obs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_Observacao))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Endereco)
                            .addComponent(lbl_Fone)
                            .addComponent(lbl_Nome)
                            .addComponent(lbl_Id))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_Nome)
                            .addComponent(tf_Fone)
                            .addComponent(tf_Endereco))))
                .addGap(74, 74, 74))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Nome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Endereco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Fone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Fone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Obs)
                    .addComponent(tf_Observacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Ultimo)
                    .addComponent(btn_Proximo)
                    .addComponent(btn_Anterior)
                    .addComponent(btn_Primeiro)
                    .addComponent(btn_Novo)
                    .addComponent(btn_Salvar)
                    .addComponent(btn_Excluir)
                    .addComponent(btn_Editar))
                .addGap(38, 38, 38)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(899, 511));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ProximoActionPerformed
   if (posicaoFornecedores<fornecedores.size()-1)
        posicaoFornecedores=posicaoFornecedores+1;
        
            mostrarFornecedores(fornecedores,posicaoFornecedores);
    }//GEN-LAST:event_btn_ProximoActionPerformed

    private void btn_AnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AnteriorActionPerformed
if (posicaoFornecedores>0)
    posicaoFornecedores=posicaoFornecedores-1;
        mostrarFornecedores(fornecedores,posicaoFornecedores);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_AnteriorActionPerformed

    private void btn_PrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PrimeiroActionPerformed
    posicaoFornecedores=0;
        mostrarFornecedores(fornecedores,posicaoFornecedores);
    }//GEN-LAST:event_btn_PrimeiroActionPerformed

    private void btn_UltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UltimoActionPerformed
    posicaoFornecedores=fornecedores.size()-1;
        mostrarFornecedores(fornecedores,posicaoFornecedores);
    }//GEN-LAST:event_btn_UltimoActionPerformed

    private void btn_NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NovoActionPerformed
    limpaCamposFornecedores();
    liberaredicaoCamposFornecedores();
    //tf_Id.setText(String.valueOf(pegaUltimoCodigoFornecedores()+1));
    
        
    }//GEN-LAST:event_btn_NovoActionPerformed

    private void btn_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalvarActionPerformed
    if ( (tf_Id.getText().isEmpty())|| (tf_Id.getText().isBlank()))
    {
    tf_Id.setText(String.valueOf(pegaUltimoCodigoFornecedores()+1));
    codigo= pegaUltimoCodigoFornecedores()+1;
    //System.out.print("\nBotao salvar codigo:"+codigo+"\n");
    String SQL = "Insert into fornecedores (IdFornecedor,NomeFornecedor,FoneFornecedor,EnderecoFornecedor,ObservacoesFornecedor) values ("+codigo+",'"+
    tf_Nome.getText()+"','"+tf_Fone.getText()+"','"+tf_Endereco.getText()+"','"+tf_Observacao.getText()+"')";
    conexao con = new conexao();
    con.conecta();
    con.executaUpdate(SQL);
    JOptionPane.showMessageDialog(null, " Registro novo gravado !");
    limpaCamposFornecedores();
    fornecedores=carregaFornecedores();
    mostrarFornecedores(fornecedores,posicaoFornecedores);
    carregarcbFornecedores();
    travaredicaoCamposFornecedores();
    }
    else
    {
      String SQL = "Update fornecedores set IdFornecedor="+Integer.valueOf(tf_Id.getText())+
              ",NomeFornecedor='"+tf_Nome.getText()+
              "',FoneFornecedor='"+tf_Fone.getText()+
              "',EnderecoFornecedor='"+tf_Endereco.getText()+
              "',ObservacoesFornecedor='"+tf_Observacao.getText()+
              "' where IdFornecedor="+Integer.valueOf(tf_Id.getText());
           
      //System.out.print("\nSQL UPDATE:"+SQL);
    
    conexao con = new conexao();
    con.conecta();
    con.executaUpdate(SQL);
    JOptionPane.showMessageDialog(null,"Registro atualizado!");
    limpaCamposFornecedores();
    fornecedores=carregaFornecedores();
    mostrarFornecedores(fornecedores,posicaoFornecedores);
    carregarcbFornecedores();
    travaredicaoCamposFornecedores();
//JOptionPane.showMessageDialog(null, "Implementar");
    }
    }//GEN-LAST:event_btn_SalvarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    mostrarFornecedores(fornecedores,posicaoFornecedores);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cb_fornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_fornecedoresActionPerformed
        try {
            
            for (int i=0;i<=fornecedores.size()-1;i++)
            {
            ////System.out.print("\nFornecedores: "+cb_fornecedores.getSelectedItem().toString());
            ////System.out.print("\nCB: "+cb_fornecedores.getSelectedItem().toString());
            if (fornecedores.get(i).getNomeFornecedor().equals(cb_fornecedores.getSelectedItem()))    
            {cbFornecedorMapa.put("Nome", fornecedores.get(i).getNomeFornecedor());
            cbFornecedorMapa.put("Id",i);
             }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        ////System.out.print("\nChave ID: "+cbFornecedorMapa.get("Id").toString());
        posicaoFornecedores = Integer.parseUnsignedInt(cbFornecedorMapa.get("Id").toString());
            mostrarFornecedores(fornecedores,posicaoFornecedores);
    }//GEN-LAST:event_cb_fornecedoresActionPerformed

    private void btn_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExcluirActionPerformed
    conexao con = new conexao();
    con.conecta();
    con.executaUpdate("delete from fornecedores where IdFornecedor ="+Integer.valueOf(tf_Id.getText()));
    fornecedores.clear();
    fornecedores =carregaFornecedores();
        mostrarFornecedores(fornecedores, posicaoFornecedores);
        carregarcbFornecedores();
    }//GEN-LAST:event_btn_ExcluirActionPerformed

    private void tf_ObservacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_ObservacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_ObservacaoActionPerformed

    private void btn_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditarActionPerformed
     liberaredicaoCamposFornecedores();
    }//GEN-LAST:event_btn_EditarActionPerformed
    public void carregarcbFornecedores(){
        //if (carregaCBFornecedores==true)
        
        fornecedores = carregaFornecedores();
        cb_fornecedores.removeAllItems();
        ////System.out.print("\n total de itens na array: "+fornecedores.size());
        for (int i =0; i<=fornecedores.size()-1;i++)
        {
        cb_fornecedores.addItem(fornecedores.get(i).getNomeFornecedor());
        }
                                            }
            
    public int pegaUltimoCodigoFornecedores()
        {
         conexao con = new conexao();
         resultado = con.executaConsulta("Select IdFornecedor from fornecedores order by IdFornecedor desc limit 1");
        
         try
         {
             resultado.next();
             codigo = (resultado.getInt(1));
        
         con.resultado.close();
         }
         catch (Exception e)
         {
         JOptionPane.showMessageDialog(null, e);
         }
        ////System.out.print("\npegaUltimoCodigoForenecedores: "+codigo+"\n");
         return codigo;
        }
    /**
     * @param args the command line arguments
     */
    public void limpaCamposFornecedores()
    { 
    tf_Id.setText("");
    tf_Nome.setText("");
    tf_Endereco.setText("");
    tf_Fone.setText("");
    tf_Observacao.setText("");
    tf_Nome.requestFocus();
    }
    
     public void travaredicaoCamposFornecedores()
    { 
    tf_Id.setEnabled(false);
    tf_Nome.setEnabled(false);
    tf_Endereco.setEnabled(false);
    tf_Fone.setEnabled(false);
    tf_Observacao.setEnabled(false);
    tf_Nome.setEnabled(false);
    }
     
    public void liberaredicaoCamposFornecedores()
    { 
    tf_Id.setEnabled(true);
    tf_Nome.setEnabled(true);
    tf_Endereco.setEnabled(true);
    tf_Fone.setEnabled(true);
    tf_Observacao.setEnabled(true);
    tf_Nome.setEnabled(true);
    } 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmFornecedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Anterior;
    private javax.swing.JButton btn_Editar;
    private javax.swing.JButton btn_Excluir;
    private javax.swing.JButton btn_Novo;
    private javax.swing.JButton btn_Primeiro;
    private javax.swing.JButton btn_Proximo;
    private javax.swing.JButton btn_Salvar;
    private javax.swing.JToggleButton btn_Ultimo;
    private javax.swing.JComboBox<String> cb_fornecedores;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_Endereco;
    private javax.swing.JLabel lbl_Fone;
    private javax.swing.JLabel lbl_Id;
    private javax.swing.JLabel lbl_Nome;
    private javax.swing.JLabel lbl_Obs;
    private javax.swing.JTextField tf_Endereco;
    private javax.swing.JTextField tf_Fone;
    private javax.swing.JTextField tf_Id;
    private javax.swing.JTextField tf_Nome;
    private javax.swing.JTextField tf_Observacao;
    // End of variables declaration//GEN-END:variables
}

